#!/usr/bin/python3
import sys, os, time, logging, threading, subprocess
from collections import OrderedDict
# Add lib dir to the include path
path = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(path, 'lib') ) 
# And import local libs
from mapper import Mapper 
from gps import GPS 

class RunMe():

    # Initialise RunMe
    def __init__(self):
        print(path)

    # Load config
    def loadconfig(self):
        print('loadconfig')

    # Loop and grab GPS data
    def loop(self):
        print("start loop")
        # Lets see if we have a new lat/lon/direction variables
        # Check if its in a zone
        # Grab parameters for that zone
        # Play audio
        # Log the action
        
# Start the application
RunMe()


