#!/bin/sh 
# Script auto-called via systemd on boot
# Or you could run: $ ./biophonic1 to start the app...

# Make sure this script is runs as root so network/mount things work
LUID=$(id -u)
if [ $LUID -ne 0 ]; then
    echo "$0 must be run as root"
    exit 1
fi

# Move to our dir so relative paths work
cd /home/sonic/bicrophonic1/src      

# Make sure wifi is up
WIFI=$(ip a | grep wlan0)
if [ ! -z "$WIFI" ];  then
    echo "wifi up"
    ip link set wlan0 up 
fi

# Cleanup any open processes
#./stop > /dev/null                  

# Check if we need to mount the SDcard Note: Could be manged by fstab...
[ -f /home/sonic/sdcard/config.json  ] || mount -t vfat -o defaults,rw,umask=0 /dev/mmcblk0p1 /home/sonic/sdcard

# Make sure we can write to the SDcard
chmod 777 /home/sonic/sdcard -R

# Setup the soundcard. Needs a little time before volume can be set
sleep 1
amixer -c 0 set PCM 100% > /dev/null  # Set initital audio volume to full

# Start the Audio Engine
/home/sonic/SonicBikeAudioEngine/bin/SonicBikeAudioEngine & > /dev/null
sleep 2

# And send a startup sound
send_osc 12345 /load 0 startup.wav
send_osc 12345 /play 0

# Check if we should just load the worms script: sudo ./start test
args=$@
if [ $# -ne 0 ]; then
    # Found an argument so lets start a test
    ./worms test & > /dev/null
else
    # otherwise start up as normal    
    # Start the map reading and gps application
    ./bicrophonic1 & > /dev/null          # Start the app

    # Release the worms! (scan for wifi and read analog input)
    ./worms wifi & > /dev/null
fi
#./adhoc.sh
