#!/bin/sh 
# Script auto-called via systemd on boot
# Or you could run: $ ./biophonic1 to start the app...

# Make sure this script is runs as root so network/mount things work
LUID=$(id -u)
if [ $LUID -ne 0 ]; then
    echo "$0 must be run as root"
    exit 1
fi

# Mount the sd card TODO: should move this to fstab...
mount -L biophonic1 -t vfat /home/sonic/sdcard -o umask=000

# Now sort the rest of the process
cd /home/sonic/bicrophonic1/src     # Move to our dir so relative paths work
./stop                              # Cleanup any open processes
sleep 1                             # Lets give the audio card time to startup
amixer -c 0 set PCM 100%            # Set initital audio volume
./bicrophonic1 &                    # Start the app
