#!/bin/sh 

# Make sure this script is runs as root so processes started by systemd can be killed
LUID=$(id -u)
if [ $LUID -ne 0 ]; then
    echo "$0 must be run as root"
    exit 1
fi

# This script called via systemd
# We use the ps aux method as it seems more reliable than a simple killall
# The killas are encapsulated in if statements so systemd reporting doesnt
# get clogged up
N=$(ps aux | grep gpsd_lua | grep -v grep)
if [ ! -z "$N" ]; then
    #killall -v gpsd_lua
    ps aux | grep gpsd_lua | awk '{ print $2}' | xargs kill -9
    #echo "killed gpsd_lua"
fi
N=$(ps aux | grep bicrophonic1 | grep -v grep)
if [ ! -z "$N" ]; then
    #killall -v bicrophonic1
    ps aux | grep bicrophonic1 | awk '{ print $2}' | xargs kill -9
    #echo "killed bicrophonic1"
fi
N=$(ps aux | grep SonicBikeAudioEngine | grep -v grep)
if [ ! -z "$N" ]; then
    ps aux | grep SonicBikeAudioEngine | awk '{ print $2}' | xargs kill -9
    #echo "killed SonicBikeAudioEngine"
fi
N=$(ps aux | grep audiotest.sh | grep -v grep)
if [ ! -z "$N" ]; then
    ps aux | grep audiotest.sh | awk '{ print $2}' | xargs kill -9
    #echo "killed SonicBikeAudioEngine"
fi
N=$(ps aux | grep worms | grep -v grep)
if [ ! -z "$N" ]; then
    ps aux | grep worms | awk '{ print $2}' | xargs kill -9
    #echo "killed SonicBikeAudioEngine"
fi
