#!/bin/sh 

# Make sure this script is runs as root so processes started by systemd can be killed
LUID=$(id -u)
if [ $LUID -ne 0 ]; then
    echo "$0 must be run as root"
    exit 1
fi

# Script called via systemd
N=$(ps aux | grep gpsd_lua | grep -v grep)
if [ ! -z "$N" ]; then
    killall gpsd_lua
    #echo "killed gpsd_lua"
fi
N=$(ps aux | grep bicrophonic1 | grep -v grep)
if [ ! -z "$N" ]; then
    killall bicrophonic1
    #echo "killed bicrophonic1"
fi
N=$(ps aux | grep SonicBikeAudioEngine | grep -v grep)
if [ ! -z "$N" ]; then
    killall SonicBikeAudioEngine
    #echo "killed SonicBikeAudioEngine"
fi

